export const SECTOR_LIST = [
  { id: 1, name: "dividend" },
  { id: 2, name: "energy" },
  { id: 3, name: "material" },
  { id: 4, name: "industrial" },
  { id: 5, name: "utilities" },
  { id: 6, name: "healthcare" },
  { id: 7, name: "financials" },
  { id: 8, name: "consumer discretionary" },
  { id: 9, name: "consumer staples" },
  { id: 10, name: "IT" },
  { id: 11, name: "communication" },
  { id: 12, name: "real estate" },
  { id: 13, name: "bond" },
  { id: 14, name: "bio tech" },
  { id: 15, name: "precious metal" },
  { id: 16, name: "base metal" },
  { id: 17, name: "agriculture" },
  { id: 18, name: "travel" },
  { id: 19, name: "alt energy" },
  { id: 20, name: "index" },
  { id: 21, name: "other ETF" },
  { id: 22, name: "other" },
  { id: 23, name: "Aerospace & Defence" },
  { id: 24, name: "retail" },
  { id: 25, name: "trading" },
  { id: 26, name: "insurance" },
];
